---
title: "R Notebook"
output: html_notebook
---

# Import packages

```{r}
library(tidyverse)
library(magrittr)
library(fitdistrplus)
library(gridExtra)
```

# Task 1

```{r}
# Read data from csv
daily_attendance <- read_csv('govhack3.csv')

glimpse(daily_attendance)
```

# Task 2

## Task 2.1

```{r}
ed_data_link <- 'govhack3.csv'
top_row <- read_csv(ed_data_link, col_names = FALSE, n_max = 1)
second_row <- read_csv(ed_data_link, n_max = 1)

column_names <- second_row %>% 
  unlist(., use.names=FALSE) %>% 
  make.unique(., sep = "__") # double underscore

column_names[2:8] <- str_c(column_names[2:8], '0', sep='__')

daily_attendance <- 
  read_csv(ed_data_link, skip = 2, col_names = column_names)

# Print list of hospital names
top_row <- as.character(top_row)
hospital_names <- top_row[top_row != "NA"]
print(hospital_names)
```

## Task 2.2

```{r}
daily_attendance <- daily_attendance %>%
  gather(key = "classified_as",
         value = "count_of_people",
         -Date) %>%
  separate(classified_as,
           into = c("type_of_visit","Hospital"),
           sep = "__") %>%
  spread(key = type_of_visit,
         value = count_of_people) %>%
  mutate(Hospital = 
           factor(Hospital,
                  levels = c(0,1,2,3,4,5,6,7,8),
                  labels = c("Royal Perth Hospital",
                             "Fremantle Hospital",
                             "Princess Margaret Hospital For Children",
                             "King Edward Memorial Hospital For Women",
                             "Sir Charles Gairdner Hospital",
                             "Armadale/Kelmscott District Memorial Hospital",
                             "Swan District Hospital",
                             "Rockingham General Hospital",
                             "Joondalup Health Campus"))) %>%
  dplyr::select(Date,Hospital,Attendance,Admissions,Tri_1,Tri_2,Tri_3,Tri_4,Tri_5)

# Changing the data types
daily_attendance <- daily_attendance %>%
  mutate(Date = as.Date(Date,"%d-%b-%Y")) %>%
  mutate(Attendance = as.integer(Attendance)) %>%
  mutate(Admissions = as.integer(Admissions)) %>%
  mutate(Tri_1 = as.integer(Tri_1)) %>%
  mutate(Tri_2 = as.integer(Tri_2)) %>%
  mutate(Tri_3 = as.integer(Tri_3)) %>%
  mutate(Tri_4 = as.integer(Tri_4)) %>%
  mutate(Tri_5 = as.integer(Tri_5))

# Missing values
daily_attendance <- daily_attendance %>%
  replace_na(list(Attendance = 0,
                  Admissions = 0,
                  Tri_1 = 0,
                  Tri_2 = 0,
                  Tri_3 = 0,
                  Tri_4 = 0,
                  Tri_5 = 0))
```


# Task 3

## Task 3.1

```{r}
fremantle_daily_attendance <- daily_attendance %>%
  filter(Hospital == 'Fremantle Hospital') %>%
  dplyr::select(Date, 
         Attendance, 
         Admissions, 
         Tri_1, 
         Tri_2, 
         Tri_3, 
         Tri_4, 
         Tri_5)

fremantle_total_attendance <- fremantle_daily_attendance %>%
  summarise(sum(Attendance))

fremantle_total_admissions <- fremantle_daily_attendance %>%
  summarise(sum(Admissions))

output_string <- sprintf("Hospital Name: Fremantle Hospital \nTotal ED Attendance: %s \nTotal Admissions: %s",
                         fremantle_total_attendance,
                         fremantle_total_admissions)

cat(output_string)
```

## Task 3.2

```{r}
hist_attendance <- fremantle_daily_attendance %>%
  ggplot(aes(x=Attendance)) + 
  geom_histogram(bins=15) + 
  labs(title = "Histogram of Attendance")

hist_admissions <- fremantle_daily_attendance %>%
  ggplot(aes(x=Admissions)) + 
  geom_histogram(bins=15) +
  labs(title = "Histogram of Admissions")

grid.arrange(hist_attendance,hist_admissions,ncol=2)
```

## Task 3.3

```{r}
fremantle_daily_attendance %>%
  filter(Date >= as.Date("2013-07-01") & Date <= as.Date("2013-07-07")) %>%
  ggplot() +
  geom_line(aes(x = Date, y = Attendance), color = "blue") + 
  geom_line(aes(x = Date, y = Admissions), color = "red") + 
  ylab('Number of People') + 
  scale_x_date(date_labels = '%b-%y\n%a',
               date_breaks = "1 day") + 
  labs(title = "Weekly Hospital Demand")

fremantle_daily_average <- fremantle_daily_attendance %>%
  mutate(Day = weekdays(Date)) %>%
  dplyr::select(-Date) %>%
  group_by(Day) %>%
  summarise_all("mean")

fremantle_daily_average$Day <- factor(
  fremantle_daily_average$Day,
  levels = c("Monday",
             "Tuesday",
             "Wednesday",
             "Thursday",
             "Friday",
             "Saturday",
             "Sunday")
)

fremantle_daily_median <- fremantle_daily_attendance %>%
  mutate(Day = weekdays(Date)) %>%
  dplyr::select(-Date) %>%
  group_by(Day) %>%
  summarise_all("median")

fremantle_daily_median$Day <- factor(
  fremantle_daily_median$Day,
  levels = c("Monday",
             "Tuesday",
             "Wednesday",
             "Thursday",
             "Friday",
             "Saturday",
             "Sunday")
)

plot_fremantle_daily_average <- fremantle_daily_average %>%
  ggplot() +
  geom_line(aes(x = Day, y = Attendance,group = 1), color = "blue") + 
  geom_line(aes(x = Day, y = Admissions,group = 1), color = "red") + 
  ylab('Number of People') + 
  labs(title = "Average Weekly Hospital Demand") + 
  theme(axis.text.x = element_text(angle = 45))

plot_fremantle_daily_median <- fremantle_daily_median %>%
  ggplot() +
  geom_line(aes(x = Day, y = Attendance,group = 1), color = "blue") + 
  geom_line(aes(x = Day, y = Admissions,group = 1), color = "red") + 
  ylab('Number of People') + 
  labs(title = "Median Weekly Hospital Demand") + 
  theme(axis.text.x = element_text(angle = 45))

grid.arrange(plot_fremantle_daily_average,plot_fremantle_daily_median,ncol=2)
```

## Task 3.4

```{r}
fremantle_daily_attendance %$%
  descdist(Attendance,boot = 100)

fremantle_daily_attendance %$%
  descdist(Admissions,boot = 100)

fremantle_daily_attendance %$%
  descdist(Tri_1,boot = 100)

fremantle_daily_attendance %$%
  descdist(Tri_2,boot = 100)

fremantle_daily_attendance %$%
  descdist(Tri_3,boot = 100)

fremantle_daily_attendance %$%
  descdist(Tri_4,boot = 100)

fremantle_daily_attendance %$%
  descdist(Tri_5,boot = 100)
```

# Task 4

## Task 4.1

```{r}
pois_estimate_tri_1 <- fremantle_daily_attendance %$%
  fitdist(data = Tri_1,
          distr = "pois")

neg_bin_estimate_tri_1 <- fremantle_daily_attendance %$%
  fitdist(data = Tri_1,
          distr = "nbinom") 

pois_estimate_tri_1 %>%
  plot

neg_bin_estimate_tri_1 %>%
  plot

pois_estimate_tri_1 %>% summary

neg_bin_estimate_tri_1 %>% summary
```